# select CAR_ID,
#     case when CAR_ID in (
#         select CAR_ID
#         from CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         where '2022-10-16' between START_DATE and END_DATE
#     ) then '대여중'
#     else '대여 가능' end as AVAILABILITY
# from CAR_RENTAL_COMPANY_RENTAL_HISTORY
# group by CAR_ID
# order by CAR_ID desc;



# SELECT DISTINCT CAR_ID,
#     CASE WHEN CAR_ID = (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#         WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
#         AND B.CAR_ID = A.CAR_ID
#     ) THEN '대여중'
#     ELSE '대여 가능' END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
# ORDER BY CAR_ID DESC




# SELECT CAR_ID,
#     CASE WHEN 
#         SUM (
#             CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
#             ELSE 0 END
#         ) > 0 THEN '대여중'
#         ELSE '대여 가능' END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC;


WITH M AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
SELECT M.CAR_ID,
    CASE WHEN CAR_ID = (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
        WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
        AND B.CAR_ID = M.CAR_ID
    ) THEN '대여중' 
      ELSE '대여 가능' END AS AVAILABILITY
FROM M
ORDER BY M.CAR_ID DESC